name: Test Ansible with secrets

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      zipfile:
        type: string
        description: zip file name
        required: true
      version:
        type: string
        description: zip file name
        required: true
      name:
        type: string
        description: zip file name
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script  
        run: |
            zip_source_path="ProHELPDESK/API/${{ github.event.inputs.name }}/${{ github.event.inputs.version }}/${{ github.event.inputs.zipfile }}"
            zip_qa_path=C:\\API\\DrugPricingApiLoyalty\\${{ github.event.inputs.zipfile }}
            jq -n --arg zip_qa_path "$zip_qa_path"  --arg zip_source_path "$zip_source_path"  '{zip_qa_path: $zip_qa_path, zip_source_path: $zip_source_path}' > params.json
            cat params.json
              
