name: Test Ansible with secrets

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo ${{ secrets.SECRET_TEST }}
      
      - name: Creating a file with content
        run: |
          touch ansiblePassword.txt
          echo ${{ secrets.SECRET_TEST }} >> ansiblePassword.txt
          cat ansiblePassword.txt
          if [${{ secrets.SECRET_TEST }} == cat ansiblePassword.txt]; echo "Success!!!"; fi
          ls -a .

          echo "ls -a ${{ github.workspace }}"
          ls -a ${{ github.workspace }}
        shell: bash

      # ansible-playbook secret.yml --vault-password-file=ansiblePassword.txt
      - name: Delete file 
        run: rm -f ansiblePassword.txt
      
      - name: Delete file 
        run: ls -a
        
      # Runs a set of commands using the runners shell
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          # Required, playbook filepath
          playbook: playbook.yml
          vault_password: ${{ secrets.VAULT_PASSWORD }}
          # Optional, directory where playbooks live
          directory: ./
          # Optional, literal inventory file contents
          inventory: |
            [local]
            127.0.0.1
            [local:vars]
            ansible_connection=local
          # Optional, additional flags to pass to ansible-playbook
          options: |
            --inventory .hosts
            --limit localhost
            --extra-vars hello=${{ secrets.SECRET_TEST }}
            --verbose
